# Generated by Django 5.0.7 on 2024-10-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_studentlist'),
        ('facultyapp', '0003_task_created_at_alter_task_content_addcourse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddCourse',
            new_name='AddCourses',
        ),
    ]
